#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정

#test-7
APP_KEY: "PSwPkxsfuRC4rmkQ5wKjnTfZzy3BRmQIsL3G"
APP_SECRET: "dg3+zaSfEnA9pzXhh0iDDIMnCMFGKYBhZdKySSfc1LY+9ZC7NOmxOaEGOK1vPJn55/nghuPMsvISiRf52jaOiMxDUmM+Opf4GArE4Oaa/v5sDlSqxpZcp+tVxSqXOEThvm7aY52qg0JlUVQW8139g1IUW9KCDcA01BGITEuc0vpgUEkafz4="

#real
#APP_KEY: "PSMpYmpvYl8XSUvIC7IIBH1hk9XC7cmdS9h7"
#APP_SECRET: "+xV5lc+d/vXI6wp7J+h+2s6QisY+WxiTiHsytBrWU3xoR+Q6ekYJ+2J91WkojaoMU+mN2zSXKgY+vq6bBLsfVokB3flGLBqgUbB3FtJ6XXpou0VupgQZ/sp2DuutuqXfAv+BDRq1fiidNTWhkunPofQGROkpktE71g6jvZkIa27rwuvAH9k="

#계좌번호 앞 8자리
CANO: "50077887"
#CANO: "63647908"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#실전투자
#URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1070247768427347988/4zipXS_3-2RbLT8FIEeIJ7g43wsrIkb1P86jIHPTEH8JWum59Os_0YF_qFyODOw9xTpB"